# Generated by Django 2.0.7 on 2020-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('title', models.CharField(max_length=32, verbose_name='疾病学科')),
                ('e_name', models.CharField(max_length=32, verbose_name='英文名')),
                ('name', models.CharField(max_length=32, verbose_name='中文名')),
                ('alias', models.CharField(max_length=32, verbose_name='别名')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
                ('expect', models.CharField(max_length=128, verbose_name='患者须知')),
                ('how_common', models.CharField(max_length=128, verbose_name='流行病学统计')),
                ('risk_factors', models.CharField(max_length=128, null=True, verbose_name='危险因素')),
                ('treatment', models.CharField(max_length=128, verbose_name='治疗方法')),
                ('self_care', models.CharField(max_length=128, verbose_name='自我诊疗')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='疾病分类')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
