# Generated by Django 2.0.7 on 2020-08-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('name', models.IntegerField(choices=[(0, 'body'), (1, 'skin'), (2, 'head'), (3, 'chest'), (4, 'stomach'), (5, 'pelvis'), (6, 'arm'), (7, 'leg')], verbose_name='身体部位')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='器官')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.body', verbose_name='对应部位')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='症状')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.organ', verbose_name='对应器官')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
