# Generated by Django 2.0.7 on 2020-08-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firstaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('orders', models.IntegerField()),
                ('c_name', models.CharField(max_length=32, verbose_name='中文症状名')),
                ('e_name', models.CharField(max_length=64, verbose_name='英文症状名')),
                ('makecall', models.CharField(max_length=128, verbose_name='呼叫指导')),
                ('do_steps', models.CharField(max_length=128, verbose_name='急救步骤')),
                ('go_doctor', models.CharField(max_length=128, verbose_name='就医判断条件')),
                ('remarks', models.BooleanField(default=False, verbose_name='是否收藏')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
