# Generated by Django 2.0.7 on 2020-08-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstaid', '0002_remove_firstaid_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstaid',
            options={'verbose_name': '急救知识', 'verbose_name_plural': '急救知识'},
        ),
        migrations.AlterModelTable(
            name='firstaid',
            table='firstaid',
        ),
    ]
