# Generated by Django 2.0.7 on 2020-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugdetail',
            name='pharmacokinetics',
            field=models.CharField(max_length=128, verbose_name='药物代谢动力学'),
        ),
    ]
