# Generated by Django 2.0.7 on 2020-08-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_auto_20200812_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aid.Company', verbose_name='对应制药公司'),
        ),
        migrations.AddField(
            model_name='drug',
            name='symptom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aid.Symptom', verbose_name='对应症状'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aid.Aid', verbose_name='对应疾病类型'),
        ),
    ]
