# Generated by Django 2.0.7 on 2020-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0005_auto_20200813_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdetail',
            name='price',
            field=models.CharField(max_length=32, null=True, verbose_name='价格'),
        ),
    ]
