# Generated by Django 2.0.7 on 2020-08-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accompany',
            options={'verbose_name': '陪诊', 'verbose_name_plural': '陪诊'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '就诊人', 'verbose_name_plural': '就诊人'},
        ),
        migrations.AlterModelTable(
            name='accompany',
            table='accompany',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
