# Generated by Django 2.0.7 on 2020-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200810_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
