# Generated by Django 2.0.7 on 2020-08-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('orders', models.IntegerField()),
                ('username', models.CharField(max_length=32, verbose_name='评论用户')),
                ('usericon', models.ImageField(default='icon/default.png', upload_to='icon', verbose_name='用户头像')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('cmt_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('cmt_rated', models.IntegerField(verbose_name='评分')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zixun.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('orders', models.IntegerField()),
                ('title', models.CharField(max_length=128, verbose_name='资讯标题')),
                ('zixun_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='courses', verbose_name='封面图片')),
                ('checked', models.IntegerField(verbose_name='阅读量')),
                ('catagorys', models.SmallIntegerField(choices=[(0, '营养'), (1, '疾病'), (2, '知道'), (3, '两性'), (4, '运动'), (5, '减肥'), (6, '母婴'), (7, '中医'), (8, '心理')], default=0, verbose_name='资讯分类')),
                ('recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '资讯',
                'verbose_name_plural': '资讯',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='news_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('orders', models.IntegerField()),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('author', models.CharField(max_length=32, verbose_name='作者名')),
                ('article', models.TextField(verbose_name='文章内容')),
                ('date', models.DateTimeField(verbose_name='发布时间')),
                ('thumbup', models.IntegerField(verbose_name='点赞数')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
