# Generated by Django 3.1 on 2020-08-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zixun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='news',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='news_detail',
            name='orders',
        ),
    ]
