# Generated by Django 2.0.7 on 2020-08-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zixun', '0003_auto_20200810_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(blank=True, default='icon/default.png', max_length=255, null=True, upload_to='news', verbose_name='封面图片'),
        ),
    ]
