# Generated by Django 2.0.7 on 2020-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zixun', '0004_auto_20200810_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cmt_rated',
        ),
        migrations.AddField(
            model_name='comment',
            name='cmt_thumbup',
            field=models.IntegerField(null=True, verbose_name='评论点赞数'),
        ),
    ]
